ECHO OFF
CLS
ECHO  
ECHO  
ECHO     Norton Utilities, Version 3.00
ECHO    
ECHO     dated Monday January 21, 1985
ECHO  
ECHO  
ECHO      This "READ ME" file provides additional information
ECHO      to supplement the Norton Utilities manual.
ECHO    
ECHO  
ECHO      You'll find the following information here:
ECHO    
ECHO       * The computers supported by the Norton Utilities, Version 3
ECHO    
ECHO       * TopView and the Norton Utilities
ECHO    
ECHO       * Special notes about the TI Professional,
ECHO           Wang PC, and NEC APC-III computers
ECHO    
ECHO    
ECHO  
PAUSE
CLS
ECHO  
ECHO       The Computers Supported by the Norton Utilities, Version 3
ECHO  
ECHO        Version 3 of the Norton Utilities work on:
ECHO        
ECHO        * All models of IBM/PC
ECHO            including the PC, PC-XT, PCjr, Portable PC, and PC-AT
ECHO        
ECHO        * All computers fully compatible with the IBM/PC, particularly
ECHO              Compaq, Compaq-Plus and Compaq Deskpro
ECHO              Data General One
ECHO              Mindset
ECHO              Panasonic Sr Partner
ECHO              Corona PC
ECHO              Tandy 1000 and 1200
ECHO              NCR PC-4
ECHO              Zenith 150
ECHO              
ECHO        * Many MS-DOS computers
ECHO            specifically including
ECHO              Texas Instruments Professional 
ECHO              Wang PC 
ECHO              NEC APC-III 
ECHO              
PAUSE
CLS
ECHO  
ECHO  
ECHO      TopView and the Norton Utilities
ECHO  
ECHO      The Norton Utilities have been specially prepared to work
ECHO      well with TopView, a windowing environment announced by IBM.
ECHO          
ECHO      TopView uses 'program information files' (PIFs) to learn the
ECHO      characteristics of programs.  The Utilities disk contains a
ECHO      NU.PIF file, for the main Norton Utilities program, NU.  
ECHO      You may use the NU.PIF information as a model for any of the
ECHO      other programs in this Utilities set.
ECHO          
ECHO      TopView places some restrictions on the Utilities' ability to
ECHO      write changes to TopView's current disk (but not other disks).
ECHO      Therefore, you may find SOME limits on these parts of the
ECHO      Utilities when they are under the supervision of TopView:
ECHO        * UnErasing (or any other disk modification) with the NU program
ECHO        * Directory sorting with the DS program
ECHO        * Disk repair with the DT program
ECHO      All other Utilities operations, including the use of NU to 
ECHO      inspect disks and DT to test disks, may be done under TopView.
ECHO  
PAUSE
CLS
ECHO        Special notes about three computers
ECHO        
ECHO        Texas Instruments Professional
ECHO        
ECHO          Before using the Utilities with the TI Pro, run EMULATE 
ECHO          to install the PC Emulator filter program.
ECHO          
ECHO        Wang PC
ECHO        
ECHO          Use of the Utilities on the Wang PC requires the ANSI
ECHO          device driver, as mentioned in the Utilities manual.
ECHO          However, the ANSI driver is an integral part of DOS 
ECHO          for the Wang PC, so it does not need to be installed by you.
ECHO          
ECHO          The main Utilities program, NU, makes special use of these
ECHO          Wang PC keys:  Prev. and Next are used as PageUp and Down;
ECHO          shift-Home is used as End (the opposite of Home);
ECHO          GL is used as a menu Escape.
ECHO       
ECHO        NEC APC-III
ECHO        
ECHO          As with the Wang PC, the ANSI driver is required and is
ECHO          automatically included in DOS.
